const UserList = [
  {
    id: 1,
    name: "John Doe",
    userName: "johndoe87",
    age: 35,
    nationality: "AMERICAN",
    friends: [
      {
        id: 3,
        name: "Ahmed Hassan",
        userName: "ahmedhassan",
        age: 42,
        nationality: "EGYPTIAN",
      },
      {
        id: 6,
        name: "John Doe",
        userName: "johndoe87",
        age: 32,
        nationality: "American",
      },
      {
        id: 7,
        name: "Jane Smith",
        userName: "janesmith95",
        age: 28,
        nationality: "British",
      },
      {
        id: 8,
        name: "Alice Johnson",
        userName: "alicej",
        age: 45,
        nationality: "Canadian",
      },
      {
        id: 9,
        name: "Mohammed Ahmed",
        userName: "m_ahmed",
        age: 36,
        nationality: "Egyptian",
      },
      {
        id: 10,
        name: "Sophia Gonzalez",
        userName: "sophia_g",
        age: 27,
        nationality: "Mexican",
      },
    ],
  },
  {
    id: 2,
    name: "Jane Smith",
    userName: "janesmith23",
    age: 28,
    nationality: "BRITISH",
    friends: [
      {
        id: 6,
        name: "John Doe",
        userName: "johndoe87",
        age: 32,
        nationality: "American",
      },
      {
        id: 7,
        name: "Jane Smith",
        userName: "janesmith95",
        age: 28,
        nationality: "British",
      },
    ],
  },
  {
    id: 3,
    name: "Ahmed Hassan",
    userName: "ahmedhassan",
    age: 42,
    nationality: "EGYPTIAN",
    friends: [
      {
        id: 1,
        name: "John Doe",
        userName: "johndoe87",
        age: 35,
        nationality: "AMERICAN",
      },
      {
        id: 6,
        name: "John Doe",
        userName: "johndoe87",
        age: 32,
        nationality: "American",
      },
    ],
  },
  {
    id: 4,
    name: "Maria Garcia",
    userName: "mariag",
    age: 30,
    nationality: "SPANISH",
  },
  {
    id: 5,
    name: "Liu Wei",
    userName: "liuwei88",
    age: 25,
    nationality: "CHINESE",
  },
  {
    id: 6,
    name: "John Doe",
    userName: "johndoe87",
    age: 32,
    nationality: "AMERICAN",
  },
  {
    id: 7,
    name: "Jane Smith",
    userName: "janesmith95",
    age: 28,
    nationality: "BRITISH",
  },
  {
    id: 8,
    name: "Alice Johnson",
    userName: "alicej",
    age: 45,
    nationality: "CANADIAN",
  },
  {
    id: 9,
    name: "Mohammed Ahmed",
    userName: "m_ahmed",
    age: 36,
    nationality: "EGYPTIAN",
  },
  {
    id: 10,
    name: "Sophia Gonzalez",
    userName: "sophia_g",
    age: 27,
    nationality: "MEXICAN",
  },
];

module.exports = { UserList };
